const mongoose = require('mongoose')

const articleSchema = mongoose.Schema({
  //author: author of the article, as id. None if the re was generated by the system.
  author: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },

  created_at: {
    type: Date
  },

  // public: whether the article is public.
  public: {
    type: Boolean,
    default: false
  },

  // requested: whether the article is requested to be public by the author.
  requested: {
    type: Boolean,
    default: false
  },

  // name: the name of the article in the URL (no spaces/capitals)
  name: {
    type: String,
    maxlength: 100,
    unique: false
  },

  // title: title of the article.
  title: {
    type: String,
    maxlength: 100
  },

  // genre: genre of the article.
  category: {
    type: String,
    maxlength: 20
  },

  // brief: brief description of the article (displayed on the homepage).
  brief: {
    type: String
  },

  // image: name of the article's image.
  image: {
    type: String,
    maxlength: 100
  },

  // text: text of the post, with re:x corresponding to the re #x.
  text: {
    type: String,
    maxLength: 160
  }
})

articleSchema.index({ author: 'text', name: 'text', title: 'text', brief: 'text', text: 'text' });

const Article = mongoose.model('Article', articleSchema)

module.exports = Article;